[tool.pytest.ini_options]
testpaths = [
    "tests"
]
markers = [
    "io: marks tests that go outside the local environment"
]

[tool.black]
line-length = 100

[tool.flake8-docstrings]
docstring-convention = "numpy"

[tool.isort]
profile = "black"

[tool.coverage.run]
source = ["src", "tests/unit"]